Remove dead social networks from share button
neocities/neocities pull request #437
Opened 2023-02-05 15:10 UTC by jeremyredhead

They are all very dead & show no signs of returning any time soon, sadly.

2023-02-11 05:43 UTC, aeiouaeiouaeiouaeiouaeiouaeiou requested changes

2023-02-11 05:43 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented on views/_share.erb
>  <a href="https://www.tumblr.com/share?<%= Rack::Utils.build_query(v: 3, u: "#{page_uri}", t: "#{site.title}") %>" target="_blank">Tumblr</a>
Perhaps a better idea is to replace these dead services with [toot for Mastodon](https://codeberg.org/kytta/toot).

```suggestion
<a href="https://www.tumblr.com/share?<%= Rack::Utils.build_query(v: 3, u: "#{page_uri}", t: "#{site.title}") %>" target="_blank">Tumblr</a>
<a href="https://toot.kytta.dev/?text=<%= Rack::Utils.build_query(u: "#{page_uri}") %>" target="_blank">Mastodon</a>
```

2023-02-21 10:33 UTC, lime360 commented
when will neocities make a mastodon server

2023-03-28 20:13 UTC, kyledrake commented
Thanks!

2023-03-28 20:13 UTC, merged